name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling get repo
        uses: actions/checkout@v2
      - name: Random command on the machine
        run: echo "Hello World... This is a FasAPI example"
